Fix: conflicts with a previous declaration in GCC 11
https://github.com/gcc-mirror/gcc/commit/b204d7722d30f44281dea3341070223475f1cff9#diff-8463625a345f2f02f0e77b2ab10215288a6a6d90659d1ae71345af3ecddaa3c3
```
../mingw.thread.h:330:24: error: 'class mingw_stdthread::thread' conflicts with a previous declaration
  330 | using mingw_stdthread::thread;
      |                        ^~~~~~
In file included from c:\msys1100\include\c++\11.0.0\thread:45,
                 from ../mingw.thread.h:28,
                 from logging.cc:20:
c:\msys1100\include\c++\11.0.0\bits\std_thread.h:62:9: note: previous declaration 'class std::thread'
   62 |   class thread
      |         ^~~~~~
```