Fix: conflicts with a previous declaration in GCC 11
https://github.com/gcc-mirror/gcc/commit/93e79ed391b9c636f087e6eb7e70f14963cd10ad#diff-5a6ec96bdb4bb5cbf2f6b26682e74429c1900ca5852e9b1a87a65eb70d79f41a
```
../mingw.mutex.h:479:24: error: 'class mingw_stdthread::once_flag' conflicts with a previous declaration
  479 | using mingw_stdthread::once_flag;
      |                        ^~~~~~~~~
In file included from ../mingw.mutex.h:40,
                 from ../mingw.condition_variable.h:52,
                 from threadpool.h:36,
                 from threadpool.cc:15:
c:\msys1100\include\c++\11.0.0\mutex:673:10: note: previous declaration 'struct std::once_flag'
  673 |   struct once_flag
      |          ^~~~~~~~~
```